[0m19:30:21.117349 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001DCF239E530>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001DCF44AA260>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001DCF44AA080>]}


============================== 19:30:21.133274 | 8126ab3b-7346-4dc3-88a9-1c6619fa8a0a ==============================
[0m19:30:21.133274 [info ] [MainThread]: Running with dbt=1.9.6
[0m19:30:21.133274 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Nitpreet Bamra\\.dbt', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt run -s fct_shopify_transactions', 'introspect': 'True', 'log_format': 'default', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m19:30:21.133274 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\Nitpreet Bamra\Desktop\shopify-monolith\shopify-monolith\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m19:30:21.133274 [debug] [MainThread]: Command `dbt run` failed at 19:30:21.133274 after 0.20 seconds
[0m19:30:21.133274 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001DCF239E530>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001DCF44AA350>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001DCF44AA320>]}
[0m19:30:21.133274 [debug] [MainThread]: Flushing usage events
[0m19:30:21.413738 [debug] [MainThread]: An error was encountered while trying to flush usage events
